spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro_web?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true